/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewTokenRouteImport } from './routes/view.$token'
import { Route as AppLiderIndexRouteImport } from './routes/_app/lider.index'
import { Route as AppPcpUsuariosRouteImport } from './routes/_app/pcp/usuarios'
import { Route as AppPcpRelatoriosRouteImport } from './routes/_app/pcp/relatorios'
import { Route as AppPcpMetasRouteImport } from './routes/_app/pcp/metas'
import { Route as AppPcpDesviosRouteImport } from './routes/_app/pcp/desvios'
import { Route as AppPcpDashboardRouteImport } from './routes/_app/pcp/dashboard'
import { Route as AppLiderDashboardRouteImport } from './routes/_app/lider.dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewTokenRoute = ViewTokenRouteImport.update({
  id: '/view/$token',
  path: '/view/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLiderIndexRoute = AppLiderIndexRouteImport.update({
  id: '/lider/',
  path: '/lider/',
  getParentRoute: () => AppRoute,
} as any)
const AppPcpUsuariosRoute = AppPcpUsuariosRouteImport.update({
  id: '/pcp/usuarios',
  path: '/pcp/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppPcpRelatoriosRoute = AppPcpRelatoriosRouteImport.update({
  id: '/pcp/relatorios',
  path: '/pcp/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPcpMetasRoute = AppPcpMetasRouteImport.update({
  id: '/pcp/metas',
  path: '/pcp/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppPcpDesviosRoute = AppPcpDesviosRouteImport.update({
  id: '/pcp/desvios',
  path: '/pcp/desvios',
  getParentRoute: () => AppRoute,
} as any)
const AppPcpDashboardRoute = AppPcpDashboardRouteImport.update({
  id: '/pcp/dashboard',
  path: '/pcp/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppLiderDashboardRoute = AppLiderDashboardRouteImport.update({
  id: '/lider/dashboard',
  path: '/lider/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/view/$token': typeof ViewTokenRoute
  '/lider/dashboard': typeof AppLiderDashboardRoute
  '/pcp/dashboard': typeof AppPcpDashboardRoute
  '/pcp/desvios': typeof AppPcpDesviosRoute
  '/pcp/metas': typeof AppPcpMetasRoute
  '/pcp/relatorios': typeof AppPcpRelatoriosRoute
  '/pcp/usuarios': typeof AppPcpUsuariosRoute
  '/lider/': typeof AppLiderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/view/$token': typeof ViewTokenRoute
  '/lider/dashboard': typeof AppLiderDashboardRoute
  '/pcp/dashboard': typeof AppPcpDashboardRoute
  '/pcp/desvios': typeof AppPcpDesviosRoute
  '/pcp/metas': typeof AppPcpMetasRoute
  '/pcp/relatorios': typeof AppPcpRelatoriosRoute
  '/pcp/usuarios': typeof AppPcpUsuariosRoute
  '/lider': typeof AppLiderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/view/$token': typeof ViewTokenRoute
  '/_app/lider/dashboard': typeof AppLiderDashboardRoute
  '/_app/pcp/dashboard': typeof AppPcpDashboardRoute
  '/_app/pcp/desvios': typeof AppPcpDesviosRoute
  '/_app/pcp/metas': typeof AppPcpMetasRoute
  '/_app/pcp/relatorios': typeof AppPcpRelatoriosRoute
  '/_app/pcp/usuarios': typeof AppPcpUsuariosRoute
  '/_app/lider/': typeof AppLiderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/view/$token'
    | '/lider/dashboard'
    | '/pcp/dashboard'
    | '/pcp/desvios'
    | '/pcp/metas'
    | '/pcp/relatorios'
    | '/pcp/usuarios'
    | '/lider/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/view/$token'
    | '/lider/dashboard'
    | '/pcp/dashboard'
    | '/pcp/desvios'
    | '/pcp/metas'
    | '/pcp/relatorios'
    | '/pcp/usuarios'
    | '/lider'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/view/$token'
    | '/_app/lider/dashboard'
    | '/_app/pcp/dashboard'
    | '/_app/pcp/desvios'
    | '/_app/pcp/metas'
    | '/_app/pcp/relatorios'
    | '/_app/pcp/usuarios'
    | '/_app/lider/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ViewTokenRoute: typeof ViewTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$token': {
      id: '/view/$token'
      path: '/view/$token'
      fullPath: '/view/$token'
      preLoaderRoute: typeof ViewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/lider/': {
      id: '/_app/lider/'
      path: '/lider'
      fullPath: '/lider/'
      preLoaderRoute: typeof AppLiderIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pcp/usuarios': {
      id: '/_app/pcp/usuarios'
      path: '/pcp/usuarios'
      fullPath: '/pcp/usuarios'
      preLoaderRoute: typeof AppPcpUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pcp/relatorios': {
      id: '/_app/pcp/relatorios'
      path: '/pcp/relatorios'
      fullPath: '/pcp/relatorios'
      preLoaderRoute: typeof AppPcpRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pcp/metas': {
      id: '/_app/pcp/metas'
      path: '/pcp/metas'
      fullPath: '/pcp/metas'
      preLoaderRoute: typeof AppPcpMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pcp/desvios': {
      id: '/_app/pcp/desvios'
      path: '/pcp/desvios'
      fullPath: '/pcp/desvios'
      preLoaderRoute: typeof AppPcpDesviosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pcp/dashboard': {
      id: '/_app/pcp/dashboard'
      path: '/pcp/dashboard'
      fullPath: '/pcp/dashboard'
      preLoaderRoute: typeof AppPcpDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lider/dashboard': {
      id: '/_app/lider/dashboard'
      path: '/lider/dashboard'
      fullPath: '/lider/dashboard'
      preLoaderRoute: typeof AppLiderDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppLiderDashboardRoute: typeof AppLiderDashboardRoute
  AppPcpDashboardRoute: typeof AppPcpDashboardRoute
  AppPcpDesviosRoute: typeof AppPcpDesviosRoute
  AppPcpMetasRoute: typeof AppPcpMetasRoute
  AppPcpRelatoriosRoute: typeof AppPcpRelatoriosRoute
  AppPcpUsuariosRoute: typeof AppPcpUsuariosRoute
  AppLiderIndexRoute: typeof AppLiderIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLiderDashboardRoute: AppLiderDashboardRoute,
  AppPcpDashboardRoute: AppPcpDashboardRoute,
  AppPcpDesviosRoute: AppPcpDesviosRoute,
  AppPcpMetasRoute: AppPcpMetasRoute,
  AppPcpRelatoriosRoute: AppPcpRelatoriosRoute,
  AppPcpUsuariosRoute: AppPcpUsuariosRoute,
  AppLiderIndexRoute: AppLiderIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ViewTokenRoute: ViewTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
