/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppLiderRouteImport } from './routes/_app/lider'
import { Route as AppPcpMetasRouteImport } from './routes/_app/pcp/metas'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLiderRoute = AppLiderRouteImport.update({
  id: '/lider',
  path: '/lider',
  getParentRoute: () => AppRoute,
} as any)
const AppPcpMetasRoute = AppPcpMetasRouteImport.update({
  id: '/pcp/metas',
  path: '/pcp/metas',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/lider': typeof AppLiderRoute
  '/pcp/metas': typeof AppPcpMetasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/lider': typeof AppLiderRoute
  '/pcp/metas': typeof AppPcpMetasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/lider': typeof AppLiderRoute
  '/_app/pcp/metas': typeof AppPcpMetasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/lider' | '/pcp/metas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/lider' | '/pcp/metas'
  id: '__root__' | '/' | '/_app' | '/login' | '/_app/lider' | '/_app/pcp/metas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/lider': {
      id: '/_app/lider'
      path: '/lider'
      fullPath: '/lider'
      preLoaderRoute: typeof AppLiderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pcp/metas': {
      id: '/_app/pcp/metas'
      path: '/pcp/metas'
      fullPath: '/pcp/metas'
      preLoaderRoute: typeof AppPcpMetasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppLiderRoute: typeof AppLiderRoute
  AppPcpMetasRoute: typeof AppPcpMetasRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLiderRoute: AppLiderRoute,
  AppPcpMetasRoute: AppPcpMetasRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
